### ISSUE TITLE
Empty Observations table after submission

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#108]
Submitting large datafiles leads to error message, file has been pushed to the database, only the Observations table appears to be empty after download.

- [x] Change the code to allow bigger files

**Comment by cmspinto** [comment]
This is a big issue, the system will have to be changed. This is because we allow submissions of 30 years of data, and a synchronous submission (the way it is now) cannot handle such a big submission. Have been in contact with Nicolas and we can change to Asynchronous submissions, but this is a real change to the process. Another way to handle this is to allow only one year to be submitted in each file.

**Comment by nicolasvanermen** [comment]
I am not convinced Carlos. I now submitted the data of NERI, it has less than 2000 observations, and these didn't make it to the database either. So please check other options before rewriting everything ...

**Comment by cmspinto** [comment]
The submission facility in the website does not use the page to call the upload anymore. 
Instead it's using a server that performs background processing. 
The server keeps a list of tasks to perform and put them in a queue.
A task can last up to 48 hours, so I expect that should be more than enough to insert the files. 

So it can happen that the user pushes the button but the task does not start immediately. 

This is an screenshot of the server that is managing the files: 
![image](https://user-images.githubusercontent.com/8705477/186862263-146745d1-2a5c-446d-baf5-40745fda3c1a.png)


And this is an example of the email that is sent to the user once the file is inserted correctly in the database: 

![image](https://user-images.githubusercontent.com/8705477/186863504-977f2124-ec5a-4261-9361-d4cb2291864c.png)

**Comment by peterdesmet** [comment]
@Osanna123 will test the submission of the whole dataset and report back.
