### ISSUE TITLE
Duplicate `sampleID`

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#135]
I'm noticing 117 duplicate `sampleID`s in the database. Technically that is possible if from different campaigns, but these are duplicates within campaigns and thus an error. Some of the IDs are repeated up to 20 times:

[dup_samples.csv](https://github.com/ices-tools-dev/esas/files/9887029/dup_samples.csv)

Campaigns in which this happens (all from righsholder `3269~2299`):

[campaigns_with_dup_samples.csv](https://github.com/ices-tools-dev/esas/files/9887030/campaigns_with_dup_samples.csv)

@nicolasvanermen did you notice anything odd when uploading these data?

**Comment by peterdesmet** [comment]
I need to investigate this further, it looks like one of the duplicate IDs that I listed, does only occur once: https://esas.ices.dk/api/getSampleRecords?sampleID=50001845

**Comment by peterdesmet** [comment]
Ok, confirmed that there is an issue. Here's an example of duplicate `sampleID`: https://esas.ices.dk/api/getSampleRecords?campaignID=775 (note the duplicate `50001845`)

But when using the duplicate sampleID as a parameter in the API, it only returns one result - maybe because the API is designed to only return 1 (the first?) result: https://esas.ices.dk/api/getSampleRecords?campaignID=50001845

**Comment by nicolasvanermen** [comment]
This is very worrying... Just checked the original file, and these duplicates are not there (kind of expected, because this is part of my personal validation and the the file screening by ICES DC). I was planning to announce the finalisation of database migration on monday to the ESAS community, but I will first check whether this problem also occurs when downloading the data through the GUI...  If so, I would like for the application to go offline again.

**Comment by peterdesmet** [comment]
Thanks @nicolasvanermen, must be an issue with the API then.

**Comment by cmspinto** [comment]
I will search this. 
I would say it's a bug but I need to research more. 

The query is returning 19 times the same records instead of returning the 19 records:

![image](https://user-images.githubusercontent.com/8705477/198965867-bcf57f71-b1e1-4fd4-8eab-13fde12acdff.png)


This is exactly the same query:

![image](https://user-images.githubusercontent.com/8705477/198966125-6f90dc2f-fadb-40f0-80cb-3c023e3b21f4.png)

I will check with a colleague of mine where the bug could be, if not will change the programming!

**Comment by nicolasvanermen** [comment]
Just thinking out loud, but I have been thinking this from the beginning... Why are these API services so important? For me this kind of issue is so fundamental! What is the use of screening data before they get in, if they come out twisted in a way that would result in errors when screening... So I have to ask this: why not let users download the data, and let them do the querying...?

**Comment by cmspinto** [comment]
From my experience more and more people use the WebAPI to fetch the results, because like that the can always work with the last version of the data.

Sorry, it was no bug, it was my fault. The Key in sample was in the wrong place. 
[https://esas.ices.dk/api/getSampleRecords?campaignID=775](https://esas.ices.dk/api/getSampleRecords?campaignID=775)
The views for downloading data and WebAPI are the same. 

@peterdesmet lazy loading is back: [https://esas.ices.dk/api/getObservationRecords?offset=0&limit=20&SpeciesCode=12010](https://esas.ices.dk/api/getObservationRecords?offset=0&limit=20&SpeciesCode=12010)

We can fill in the record count in the future, but then it needs to be tested. 
What have done is simply calling the counting from the object before doing the pagination, this means that it needs to "execute" the query before the pagination and it makes it much more slow. 
Doing this was also free of errors because it's the same object that is returned. 

I can of course create a "counting query" with the same filters that are applied to the output data. 
Doing means that these will be two distinct objects accessing the database and while one is a filter to the data "in a lazy way", the other one will be a full string query (for counting), that is why this would need to be checked.

**Comment by peterdesmet** [comment]
Thanks @cmspinto. I for one am happy there is an API. Odd that the bug only occurred there and not in the download service.

I'll test lazy loading. 👍  For now I'm fine nothing having a count or `endOfResults`

**Comment by nicolasvanermen** [comment]
All good, but can we agree that all API stuff needs to be tested thoroughly?  I still think it is crazy that we put so much time and effort in screening input, and that we would not do the same for API output. But I cannot work with the API (I only know IPA), so this should be done internally at ICES or by you Peter.

**Comment by peterdesmet** [comment]
I'm using the API for https://github.com/inbo/esas2obis. I discovered the issues by testing the data I'm getting back there.

**Comment by nicolasvanermen** [comment]
OK so you are confident that this was the only bug?

**Comment by peterdesmet** [comment]
So far I haven't encountered any others... but this bug and limited time to test have also prevented me from testing more thoroughly.

**Comment by cmspinto** [comment]
> OK so you are confident that this was the only bug?

Yep, even with thin one I'm a bit surprised.
