### ISSUE TITLE
Review observations: euring_species_code

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#14]
Updated todo:

- [x] Rename field to `species_code` because one should be able to submit both EURING and APHIA ids
- [x] Decide how to differentiate between EURING and APHIA ids (both are integers). Maybe with a prefix `euring:` With extra field  `SpeciesCodeType`
- [x] Remove non biological codes: 40fecb4
- [x] Understand use of `~`: it means **and** not **or** and can thus not be used for species_code
- [x] ~~Use `~` for combinations: 2645b2e~~
- [ ] Have reference for marine mammals (not in EURING?)
- [x] ~~Add field `vernacular_name` (see #46)~~
- [ ] Request necessary missing codes to be added to EURING
- [ ] Request necessary missing APHIA codes to be added to WORMS

---

`euring_species_code` is where one provides **scientific name** information. ESAS has relied on EURING codes for these, which - in contrast with many other taxonomic codes (like `aphia_id`) - allow to record observations where it was hard to identify the species. These uncertain identifications can be more precise that a shared taxonomic level:

- `unidentified wader`
- `unidentified small gull`
- `Uria aalge / Alca torda`: more precise than "Alcidae"

It might not be possible to translate all of these to `aphia_id`.

Through its history, ESAS has also invented some codes that do not exist in EURING (see both columns on [this page](https://ices-tools-dev.github.io/esas/species/)), especially non-birds and objects.

My suggestion would be that data providers submit the `scientific_name` (so we don't loose information) in addition to an `aphia_id` (where possible)

**Comment by nicolasvanermen** [comment]
To follow up on this: 6345 is an unambiguous code among the ESAS community,
yet "scientifically" it can be written in many different ways: Uria aalge /
Alca torda,  Alca torda / Uria aalge, Alca torda/Uria aalge. How should we
anticipate this? The same problem may occur due to ever changing taxonomy
and nomenclature...

When I mentioned we should be careful with re-coding while aiming to
encourage the ESAS community in actual future updates, maintaining current
species codes is exactly what I was referring to... "710" is as familiar as
"northern gannet" to anyone involved. Note that we have six months of
intense discussion on this behind us already.

What I propose is the following:
1) data are submitted applying historical ESAS codes (mainly based on
Euring). In the controlled vocabulary these codes are linked to whatever is
necessary: Euring translation, IOC nomenclature, alphia_id,...
2) if necessary, data can be extracted only supplying the alphia_id, but
then again what would possibly be wrong with including the ESAS code and
scientific naming in the exported files as well?











Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Thanks @nicolasvanermen, I had no idea that the codes `710` are a core aspect of the ESAS methodology. They should be kept then. And used as such when submitting.

@ices-tools-dev/data-and-information It would be great if a translation table with those codes to `scientific_name` and `aphia_id` is part of the database, so that those fields can be included in exports. We can help provide the data to populate that table.

**Comment by nicolasvanermen** [comment]
OK Peter, I will try to supply such a translation table by the next
meeting. As discussed among us, it should be clear that during some
surveys, species groups such as *Uria aalge */ *Alca torda *or *Gavia *sp.
are *never* determined to species level, and these species groups are
therefore regularly used as a 'taxonomic unit' in analyses regarding
anthropogenic impact and so on. Clearly, we have no problem with
Alphia_ID's, only this should co-exist with the historical way of coding,
and missing values should be tolerated for the Alphia_ID column...


Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by nicolasvanermen** [comment]
[euring_species_code.xlsx](https://github.com/ices-tools-dev/esas/files/5643329/euring_species_code.xlsx)
I performed a match of the ESAS/EURING codes with Alphia_ID's, using a most handy tool from the WoRMS website. Where the match failed I tried to look for the most appropriate match manually and moved up in the taxonomic tree where necessary. These manual matches are indicated in red font. Quite some codes are still left open though (yet these including anthropogenic objects which will preferably be deleted before the migration). 
Peter, how do we continue, can you update the species table on the github repository using this file?

**Comment by nicolasvanermen** [comment]
[euring_species_code_matched.xlsx](https://github.com/ices-tools-dev/esas/files/5643355/euring_species_code_matched.xlsx)

**Comment by peterdesmet** [comment]
Thanks Nicolas! I have copied the `aphia_id` and `aphia_scientific_name` information to the [csv file](https://github.com/ices-tools-dev/esas/blob/main/_data/vocabularies/euring_species_code.tsv) in this repository. Work from that file if you want to make further changes. I have also updated the template, so on the website you now have the name + a direct link to WoRMS: https://ices-tools-dev.github.io/esas/species/

Note 1: I only kept 2 columns and no colours, because accepted taxa can be retrieved from WoRMS and we can make a distinction between exact and higher matches via a script if needed.

Note 2: I have removed the generic Phylloscopus for species records and removed the very broad Cetacea for some more specific records. I have also corrected the error that from the Cetacean onwards all records were shifted by two lines.

On data completeness:

1. For numerous taxa, the species is just missing in WoRMS. We could contact them to add it.
2. For some taxa, the match with WoRMS will be to something higher in the classification, making it less precise (hence also the need to keep EURING codes)
3. Some codes are indeed anthropogenic objects which will never match.

**Comment by nicolasvanermen** [comment]
OK, great! Looks good.

Couldn't find any shift in records in the original csv though... Can you show me where that occurs? Just to be sure that this does not go back to the original lookup table.

I also see _Phylloscopus_ is still in there? Which is good, because analogue to _Turdus_, _Podiceps_, and many other taxa defined at genus level.

One more general remark: The original file gives two 'matches', represented by the columns 'AphiaID' and 'AphiaID_accepted', not sure which is the preferred option. Mostly these are the same, but not always. For example _Thalasseus sandvicensis_ has an Aphia ID with status unaccepted, and is linked to _Sterna sandvicensis_ with another, yet accepted, Aphia ID. Which one should we use? Can we get some input from ICES here?

**Comment by neil-ices-dk** [comment]
yes - we use the 'accepted' label (and preserve the original name/match either as an additional field or in a lookup table);

**Comment by peterdesmet** [comment]
Hi @nicolasvanermen the shift must then have occurred on my end.

Regarding `accepted`: I have matched as originally as possible in the species list, as accepted names can always be retrieved through services (and might change over time). But of course fine if ICES implements this as @neil-ices-dk suggests (as long as the original match is retained somewhere).

**Comment by cmspinto** [comment]
I think we can retain the original name, we will have to discuss this when we finalize the format. 
Like it was proposed we can allow this only for historical files.

**Comment by peterdesmet** [comment]
@cmspinto, to summarize (correct me if wrong):

- ESAS users can continue to upload their data with an `euring_species_code`
- This code will be mapped during upload to a taxon table (with an original name, accepted name, and where known WoRMS code).
- Users will be informed when a match is not found (**what should they do then?**)
- When downloading data, the original code, the scientific name and aphia_id will be included

@nicolasvanermen: given that technically not all values in this field are Euring codes, shouldn't we rename this to `species_code` or `esas_species_code`?

**Comment by nicolasvanermen** [comment]
Yes, that is correct, esas_species_code would be better.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by nicolasvanermen** [comment]
In case there is no match and this is not due to an erroneous entry, the
species_table should  be added with the new value by someone at ICES I
guess. Not sure how easy this will be? This will actually occur sometimes,
as the species list as it is now is mainly based on earlier observations,
and therefore not exhaustive!

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
We'd need to discuss this point tomorrow.
a bit of additional information: 
We have a reference list SFLAG (https://vocab.ices.dk/?ref=46), where we have codes SPxx that a submitter can use to identify number of species in the observed group. The list could complement the WoRMS references.
We can adopt reporting of multiple codes in a field with use of tilda (~)

**Comment by peterdesmet** [comment]
@Osanna123 question regarding the use of `~` (see also 2645b2e). Does that mean `40~50`:

1. I saw both Gavia immer and Gavia adamsii
2. I saw a bird that is either Gavia immer or Gavia adamsii

**Comment by peterdesmet** [comment]
https://github.com/ices-tools-dev/esas/issues/14#issuecomment-790822344 is now answered. Tildes mean **and** and can thus not be used in the species list (where the intended meaning is **or**). Updated in fe7d4c0

**Comment by peterdesmet** [comment]
Taxonomic information has been discussed and is included. Closing issue.
