### ISSUE TITLE
Review positions: beaufort

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#25]
`positions: beaufort` indicates the sea state with an integer Beaufort code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/positions.yaml#L90-L105

- [x] @ices-tools-dev/data-and-information Does ICES use the Beaufort scale for any other dataset? **no**
- [x] @nicolasvanermen wouldn't it technically be better if `sea_state` was used as a name for the field or is `beaufort` easier?

**Comment by nicolasvanermen** [comment]
Sea state has a scale of its own (which is a simplification of the beaufort
scale with 9 instead of 12 values). Actually, this field was named
sea_state before, yet used the beaufort scale. Quite confusing, I suggest
keeping beaufort as a column name.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
New vocab

**Comment by peterdesmet** [comment]
Hi @Osanna123, by "New vocab" I assume here is not existing one to reuse and no further action is required on ESAS part?

**Comment by peterdesmet** [comment]
Ok, you can re-open any of the issues where that is necessary.
