### ISSUE TITLE
Review positions: visibility

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#26]
`positions: visibility` indicates the visibility with a letter or number code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/positions.yaml#L125-L153

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? Is this field used in other datasets? **no**
- [x] @nicolasvanermen Would it be possible to translate the letters A-D to a number (e.g. upper bound or mean), so we just have a range of numbers with min-max for all? How is this used in analyses?

**Comment by nicolasvanermen** [comment]
A, B, C, D are well-established codes that used to describe
visibility 'quality' instead of an actual distance range (these were added
later). Was always coded as such in the ESAS v5 database, therefore I would
keep it in. Yet it would be nice to make clear that visibility is
preferably scored using distance.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen "Yet it would be nice to make clear that visibility is preferably scored using distance." Can you write something that would fit in the definition?

**Comment by nicolasvanermen** [comment]
Visibility code, preferably scored as a distance (A, B, C & D being
historical codes):

   - A Poor (< 1 km)
   - B Fair/moderate (1 – 5 km)
   - C Good/very good (5 – 10 km)
   - D Excellent/infinity (> 10 km)
   - 0.1 Visibility in km
   - 0.2 Visibility in km
   - 0.3 Visibility in km
   - 0.4 Visibility in km
   - 0.5 Visibility in km
   - 0.6 Visibility in km
   - 0.7 Visibility in km

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen please see my change at https://github.com/ices-tools-dev/esas/commit/146d9ea71c2600e3a0dfc7605c570622d3c06981

**Comment by Osanna123** [comment]
need new vocab
