### ISSUE TITLE
Review trips/positions/observations: "notes"

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#50]
At what level (if any) do we need `notes`?

**Comment by nicolasvanermen** [comment]
We at INBO mainly use it at observation level, to be able to give some more details on specific observations. I think it is useful. For example, when a shag is seen on a turbine foundation, we can give details on the turbine number, which is difficult to deduct from the observation position alone. Personally, I would keep it there.
 
On the other hand, regarding data analyses, it will most probably never be used... It was not part of the official ESAS v5 data model neither. 

Another reason for holding on to the notes fields could be the aim the ICES ESAS database downloads to function as the reference database even for the data providers themselves. But due to the many specifications involved in this migration process I am afraid we are already far beyond this option...

**Comment by peterdesmet** [comment]
This field is now added to `Campaign` (campaign info), `Sample` (e.g. to not lose old ship names) and `Observation`. Not for `Position`, since not necessary. That should be sufficient for data providers to use the ESAS database for their own purposes.
